swagger: '2.0'
info:
  version: 1.0.0
  title: Based on "Basic Auth Example"
  description: >
    An example for how to use Auth with Swagger.

host: basic-auth-server.herokuapp.com

paths:
  /bookings:
    get:
      summary: Menampilkan list booking semuanya
      description: >
        Endpoint ini digunakan untuk mendapatkan list seluruh daftar booking.
      tags: 
        - Bookings
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 'Menampilkan data `bookings`'
        '401': 
          description: 'You do not have necessary permissions for the resource'

  /bookings/{id}:
    get:
      summary: Menampilkan data booking
      description: >
        Endpoint ini digunakan untuk mendapatkan data booking tertentu.
      tags: 
        - Bookings
      security: 
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          type: number
          required: true
          description: id data booking yang akan ditampilkan
          example: 1
      responses:
        200:
          description: 'menampilkan data booking tertentu'




  /bookings/{id}/join:
    put:
      summary: Gabung group booking
      description: >
        Endpoint ini digunakan user unuk bergabung dengan agenda booking yang sudah ada.
      security: 
        - bearerAuth: []
      tags: 
        - Bookings
      parameters:
        - in: path
          name: id
          type: number
          description: id booking untuk user dapat bergabung.
          required: true
          example: 1
      responses:
        200:
          description: 'pesan Selamat bergabung'


  /bookings/{id}/unjoin:
    put:
      summary: Batal gabung group booking
      description: >
        Endpoint ini digunakan user unuk keluar dari agenda booking yang sudah ada.
      security: 
        - bearerAuth: []
      tags: 
        - Bookings
      parameters:
        - in: path
          name: id
          type: number
          description: id booking yang telah terdaftar.
          required: true
          example: 1
      responses:
        200:
          description: 'pesan Berhasil keluar dari group'



  /schedules:
    get:
      tags: 
        - Bookings
      security:
        - bearerAuth: []
      responses:
        200:
          description: berhasil mendapatkan daftar schedules

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
